###  安装numpy库：


```python
pip install numpy
import numpy as np
```


###  创建二维数组：
```python
arr2=np.array([[1,2,3],[4,5,6]])
```

最左侧有几个中括号就代表为几维数组


返回数组维度print(arr2.ndim)  #ndim 数组维度


返回数组各个维度元素数量：print(arr2.shape) #shape各个维度元素的数量


其他还有：size:元素总个数  dtype返回数组元素类型(如int64，表示64bit长度整数)


np.zeros(3)#返回三个元素值均为0的array


np.ones(5)#返回五个元素值均为1的array


注意：以上两种方法返回的数值类型均为float


np.arange(初始值，末尾值，步长)



###  array与list异同：


相同：都支持索引切片迭代


不同：array内部所有元素数据类型必须相同，list没有这个要求

In [1]:
import numpy as np

In [3]:
arr1=np.array([6,2,-7,2,8,-2,1])
arr1

array([ 6,  2, -7,  2,  8, -2,  1])

In [5]:
arr2=np.array([[1,3,5],[2,4,6]])
arr2

array([[1, 3, 5],
       [2, 4, 6]])

In [8]:
print(arr1.ndim)
print(arr2.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr1.size)
print(arr2.size)
print(arr1.dtype)
print(arr2.dtype)

1
2
(7,)
(2, 3)
7
6
int32
int32


In [12]:
arr3=np.zeros(6)
arr4=np.ones(5)
arr5=np.arange(10,21,2)
print(arr3)
print(arr4)
print(arr5)

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[10 12 14 16 18 20]


In [19]:
#连接两个数组：
array6=np.concatenate([arr1,arr3])#要求要拼接的数组的维度相同
array6

array([ 6.,  2., -7.,  2.,  8., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.])

In [ ]:
#对数组内容进行排序：sorted
#第一种方法：
sorted_array6=sorted(array6)
sorted_array6
#sorted调用后只返回排序好的新数组，不改变原有数组

#第二种方法：
array5=arr5
array5.sort()
print(array5)
#sort什们都不返回，但会改变原始数组

# 数组的索引和切片
正向：012345...


反向：-1，-2，-3...


切片：arr1[1:4]#索引第一到三个元素


# 数组的数学计算
前提：数组维度相同，数组内元素数量相同


不同数组之间相互进行四则运算，本质是数组的相同位置对应元素之间进行相互加减乘除


max min sum求和 mean求平均值


例子：arr1.mean()  #求数组内所有元素的平均值


# 根据特定条件筛选数组中的特定值
例子：arr=([-22,3,65,8,11,7])
arr[arr>6]
输出筛选大于6的元素


# python逻辑运算符
与and:&


或or:|


非not: ~


In [25]:
arr=np.array([-22,3,65,8,11,7])
arr[(arr>6) & (arr<10)]

array([8, 7])

In [41]:
arr1=np.array([1,3,2,4,9])
arr2=np.ones(5)
arr3=np.zeros(3)

#数组4要求拼接数组123
arr4=np.concatenate([arr1,arr2,arr3])
arr4

#对数组1进行排序
arr1.sort()
print(arr1)

#索引数组1第三个元素和第二到第四个元素
print(arr1[2])
print(arr1[1:4])

#arr1与arr2相加
arr_sum=arr1+arr2
print(arr_sum)

#arr1中各个元素与-5相乘结果
arr1* -5

#打印arr1的最大值最小值求和和平均值
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.mean())

#筛选arr1中所有小于1或大于3的数字，并打印出来
print(arr1[(arr1<1)|(arr1>3)])

[1 2 3 4 9]
3
[2 3 4]
[ 2.  3.  4.  5. 10.]
9
1
19
3.8
[4 9]
